### PR TITLE
aligned articles 31 & 32

### PR DESCRIPTION
**Pull request by millicentochieng**

### CODE REVIEW

**Comment by Freshia** [comment]
@millicentochieng , the files do not seem to be aligned. For example, I've done a quick check with line 1473 of both files, it does not have equivalent sentences

**Comment by Freshia** [comment]
The PR title says you've aligned till article 32, but your commit shows differences up until article 34. Not sure if you intended to align till article 34 @millicentochieng

**Comment by millicentochieng** [comment]
Sorry @Freshia I only aligned 2 articles 31 and 32. For 33 and 34 I only changed the numbering.

**Comment by Freshia** [comment]
> Sorry @Freshia I only aligned 2 articles 31 and 32. For 33 and 34 I only changed the numbering.

No problem! Thanks for the updates! :)

**Pull request merged**
